RDS Storage type and parameters
jetbrains-infra/terraform-aws-rds-mysql pull request #5
Opened 2023-10-31 14:29 UTC by AndreyMulin

2023-10-31 17:54 UTC, chrkv approved these changes

2023-11-09 11:28 UTC, sugdyzhekov requested changes

2023-11-09 11:28 UTC, sugdyzhekov commented on variables.tf
> +  default     = "gp2"
I don't like the default value, let's set the `gp3`

2023-11-09 11:28 UTC, sugdyzhekov commented on variables.tf
>      ModuleVersion = "v0.4.0"
Please set `v0.5.0`

2023-11-09 11:34 UTC, sugdyzhekov approved these changes

2023-11-09 11:34 UTC, merged